[UXP-199] fix some tests
tests are still not completing because of the following error on multiple files:
 NullInjectorError: R3InjectorError(Standalone[ThumbnailComponent])[FileService -> FileService -> FileService -> DspaceRestService -> HttpClient -> HttpClient]:
                                                                                     NullInjectorError: No provider for HttpClient!